language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
notifications:
  email: false
before_script:
  - composer self-update
  - COMPOSER=composer.travis.json composer install
  - export PATH=`pwd`/vendor/bin:$PATH
script:
  - phpunit
