language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
notifications:
  email: false
before_script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - composer install
  - export PROJECTROOT=`pwd`
  - export PATH=`pwd`/vendor/bin:$PATH
  - ${PROJECTROOT}/test/phpunit/install.sh
  - which phpunit
  - which phantomjs
script:
  - ${PROJECTROOT}/test/test.sh
