language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
notifications:
  email: false
before_script:
  - composer self-update
  - composer install
  - export PROJECTROOT=`pwd`
  - export PATH=`pwd`/vendor/bin:$PATH
  - composer install --working-dir ${PROJECTROOT}/test/phpunit/v6
  - which phpunit
  - which phantomjs
script:
  - phpunit
